apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tfjobs.kubeflow.org
spec:
  group: kubeflow.org
  scope: Namespaced
  names:
    kind: TFJob
    singular: tfjob
    plural: tfjobs
  versions:
  - name: v1
    served: true
    storage: true
  - name: v1beta2
    served: true
    storage: false
  subresources:
    status: {}
  # new
  preserveUnknownFields: true  
  validation:
    openAPIV3Schema:
      # new
      type: object
      properties:
        spec:
          # new
          type: object
          properties:
            tfReplicaSpecs:
              # new
              type: object
              properties:
                # The validation works when the configuration contains
                # `Worker`, `PS` or `Chief`. Otherwise it will not be validated.
                Worker:
                  # new
                  type: object
                  properties:
                    replicas:
                      type: integer
                      minimum: 1
                PS:
                  # new
                  type: object
                  properties:
                    replicas:
                      type: integer
                      minimum: 1
                Chief:
                  # new
                  type: object
                  properties:
                    replicas:
                      type: integer
                      minimum: 1
                      maximum: 1
